package com.ngash.portfolio.portfolio_backend.dto;

import jakarta.validation.constraints.*;
import lombok.*;

@Getter
@Setter
public class ContactRequest {

    @NotBlank
    private String firstName;

    @NotBlank
    private String lastName;

    @Email @NotBlank
    private String email;

    @NotBlank
    private String message;

    @NotNull
    private Boolean dataConsent;

    private boolean marketingConsent;

      //setters and getters are generated by Lombok's @Getter and @Setter annotations
    
}
